config/routes.rb
Tele2::Application.routes.draw do

  root 'reports#index'
  get 'reports' => 'reports#index', as: :reports
  get 'reports/:to_date' => 'reports#show', as: :report

  resources :groups

  get 'login' => 'sessions#new', as: :vk_login
  get 'logout' => 'sessions#destroy', as: :vk_logout
  get 'callback' => 'sessions#callback', as: :vk_callback

  

end

app/models/group.rb
class Group < ActiveRecord::Base

  has_many :posts, dependent: :destroy

  validates :url, format: {with: /(http(s)?:\/\/)?vk.com\/\w+(\/)?/}, presence: true
  validates :screen_name, uniqueness: true, presence: true

  default_scope -> { order 'screen_name ASC' }

  def url= attr
    super attr
    self.screen_name = attr.match(/vk.com\/([\w\W]+)\/?/)[-1]
  end

  def self.make_report from, till
    joins(:posts).select(
        'groups.*',
        'SUM(posts.likes_count) AS likes_count',
        'SUM(posts.comments_count) AS comments_count',
        'SUM(posts.reposts_count) AS reposts_count'
    ).where(
        'posts.published_at' => from..till
    ).group(
        'posts.group_id',
        'groups.id'
    )
  end

  def self.make_xls_report from, till
    till+=1
    relation = joins(:posts).select(
        'groups.*',
        'SUM(posts.likes_count) AS likes_count',
        'SUM(posts.comments_count) AS comments_count',
        'SUM(posts.reposts_count) AS reposts_count'
    ).where(
        'posts.published_at' => from..till
    ).group(
        'posts.group_id',
        'groups.id'
    ).order('groups.screen_name ASC')
    xls = Axlsx::Package.new
    time_style = xls.workbook.styles.add_style :num_fmt => Axlsx::NUM_FMT_YYYYMMDDHHMMSS
    sheet = xls.workbook.add_worksheet name: 'Статистика'
    sheet.add_row ['группа', 'лайки', 'комментарии', 'репосты']
    relation.each_with_index do |group, index|
      sheet.add_row [group.screen_name, group.likes_count, group.comments_count, group.reposts_count]
      sheet.add_hyperlink :location => "##{group.screen_name}", :ref => "A#{index+2}"
    end
    relation = includes(:posts)
    .where(
        'posts.published_at' => from..till
    ).group(
        'posts.id',
        'posts.group_id',
        'groups.id'
    ).order('posts.published_at DESC').references(:posts)
    wrap_text_style = xls.workbook.styles.add_style alignment: { wrap_text: true }, height: 'auto'
    relation.each do |group|
      sheet = xls.workbook.add_worksheet name: group.screen_name
      sheet.add_row ['Дата', 'Текст', 'URL', 'Кол-во лайков', 'Кол-во комментариев', 'Кол-во репостов']
      posts_count = 1
      group.posts.each do |post|
        posts_count+=1
        post_text = post.text.gsub(/<\/?[^>]+?>/, '')
        row = sheet.add_row [post.published_at, post_text, "#{group.url}?w=wall-#{group.gid}_#{post.vk_id}", post.likes_count, post.comments_count, post.reposts_count], style: [time_style, wrap_text_style, nil, nil, nil, nil]
        text_column_width = 408
        row_height = (post_text.length*8+5)/text_column_width*20
        row.height = row_height<23 ? 30 : row_height
      end

      sheet.add_row [nil, nil, "=SUM(D2:D#{posts_count})", "=SUM(E2:E#{posts_count})", "=SUM(F2:F#{posts_count})"]
      sheet.column_info[0].width=17
      sheet.column_info[1].width=50
      sheet.column_info[3].width=12
      sheet.column_info[4].width=18
      sheet.column_info[5].width=13
    end
    xls
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :group
  paginates_per 10

  class << self

    %i{likes reposts comments}.each do |resource|
      method_name = "#{resource}_count"
      define_method method_name do
        select("sum(#{method_name}) as #{method_name}")[0].send(method_name) || 0
      end
    end

  end


end

app/models/report.rb
class Report < ActiveRecord::Base

  belongs_to :group

  delegate :screen_name, to: :group

  default_scope -> { order 'to_date DESC' }


  def self.make_report to_date
    joins(:group).where(to_date: to_date).select 'reports.*',
                                                 'groups.screen_name AS screen_name',
                                                 'groups.url AS group_url',
                                                 'groups.screen_name AS group_screen_name'
  end

  def self.dates_between from, to
    where('to_date BETWEEN ? AND ?', from, to).select('DISTINCT reports.to_date').map &:to_date
  end

  def dated? check_date
    date == format_date(check_date)
  end

  def date= attr
    super format_date(attr)
  end

  private

    def format_date attr_date
      case attr_date
        when Date then attr_date
        when Numeric then Time.at(attr_date).to_date
        when Time then attr_date.to_date
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include ReportsHelper

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @group = Group.new
  end

  def create
    @group = Group.new group_params
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find params[:id]
    @posts = @group.posts.where('published_at BETWEEN ? AND ?', date_from, date_to)
    @likes_count = @posts.likes_count
    @comments_count = @posts.comments_count
    @reposts_count = @posts.reposts_count
    @posts = @posts.order('published_at DESC').page params[:page]
  end

  def destroy
    @group = Group.find params[:id]
    @group.destroy
    redirect_to :back
  end

  private

    def group_params
      params.require(:group).permit(:url)
    end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def index
    respond_to do |format|
      format.html {
        @groups = Group.make_report date_from, date_to
      }
      format.xls {
        send_data Group.make_xls_report(date_from, date_to).to_stream.read,
                  type: "text/xls; charset=utf-8; header=present",
                  filename: "Tele2 Social Report (#{date_from} - #{date_to}).xlsx"
      }
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # генерируем случайный state
    srand
    session[:state] ||= Digest::MD5.hexdigest(rand.to_s)
    # и URL страницы авторизации
    @vk_url = VkontakteApi.authorization_url(scope: [:wall, :friends], state: session[:state])
  end

  def callback
    # проверка state
    if session[:state].present? && session[:state] != params[:state]
      redirect_to root_url, alert: 'Ошибка авторизации, попробуйте войти еще раз.' and return
    end

    # получение токена
    @vk = VkontakteApi.authorize(code: params[:code])
    # и сохранение его в сессии
    session[:token] = @vk.token
    # также сохраним id пользователя на ВКонтакте - он тоже пригодится
    session[:vk_id] = @vk.user_id

    redirect_to root_url
  end

  def destroy
    session[:token] = nil
    session[:vk_id] = nil

    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
require 'uri'

module GroupsHelper

  def vk_post text=''
    uris = URI.extract text, ['http', 'https']
    result = text.dup
    uris.each do |uri|
      result.gsub! uri, "<a href=\"#{uri}\" target=\"_blank\">#{uri}</a>"
    end
    raw result
  end

end

app/helpers/reports_helper.rb
module ReportsHelper

  def date_from
    params[:date_from] ? Date.parse(params[:date_from]) : Date.today.beginning_of_month.last_month
  end

  def date_to
    params[:date_to] ? Date.parse(params[:date_to]) : Date.today.beginning_of_month-1
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/groups/index.html.slim
.col-xs-12
  = link_to 'Создать группу', new_group_path, method: :get, class: [:btn, 'btn-primary']
  br
  br
  table.table.table-striped.table-condensed
    tr
      th Название
      th
    - @groups.each do |group|
      tr
        td = link_to group.screen_name, group_path(group)
        td = link_to group_path(group), method: :delete, confirm: 'Удалить эту группу?' do
          i.icon-remove

app/views/groups/new.html.slim
.col-xs-3
.col-xs-6
  = form_for @group do |t|
    .input-group
      = t.text_field :url, placeholder: 'Введите адрес новой группы', class: 'form-control'
      span.input-group-btn
        = t.submit 'Создать', class: [:btn, 'btn-default']

app/views/groups/show.html.slim
.col-xs-12
  = link_to 'назад', :back
  h1 = link_to @group.screen_name, @group.url, target: :blank
  h2
    = date_from
    |  -
    |  #{date_to}
  h3
    | лайков: #{@likes_count},
    |  репостов: #{@reposts_count},
    |  комментариев: #{@comments_count}
  = paginate @posts
  - @posts.each do |post|
   .post
     .date = link_to post.published_at, "http://vk.com/feed?w=wall#{post.author_id}_#{post.vk_id}", target: :blank
     .text = vk_post post.text
     .likes-count.fa.fa-heart = post.likes_count
     .comments-count.fa.fa-comment = post.comments_count
     .reposts-count.fa.fa-retweet = post.reposts_count

  = paginate @posts

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Tele2 Social Tool"
    = csrf_meta_tags

    = stylesheet_link_tag "application", media: :all
    = javascript_include_tag "application"

  body
    nav.navbar.navbar-default
      .container
        .navbar-header
          = link_to "Tele2 Social Tool", root_path, class: 'navbar-brand'
        #navbar
          ul.nav.navbar-nav
            li = link_to "Отчеты", root_path
            li = link_to "Группы", groups_path

    .container-fluid
      .row
        = yield

app/views/reports/index.html.slim
.col-xs-12
  = form_tag '/', method: :get, id: 'filter' do
    = hidden_field_tag 'format', 'html'
    = hidden_field_tag 'date_from', controller.date_from, id: 'date-from'
    = hidden_field_tag 'date_to', controller.date_to, id: 'date-to'
    h3.text-center
      | Статистика за период
      span#reportrange
        span
      i.fa.fa-file-excel-o#btn-download-xls
  table.table.table-striped
    tr
      th Группа
      th Лайки
      th Репосты
      th Комментарии
    - @groups.each do |group|
      tr
        td = link_to group.screen_name, group_path(group, date_from: date_from, date_to: date_to)
        td = group.likes_count
        td = group.reposts_count
        td = group.comments_count

javascript:
  window.dateFrom = "#{controller.date_from}";
  window.dateTo = "#{controller.date_to}";